sources:
  in:
    type: "demo_logs"
    format: "apache_common"
    interval: 2

transforms:
  remap:
    type: remap
    inputs:
      - in
    source: |
      .font = "Inconsolata"
      .output = "json"

sinks:
  out:
    type: http
    uri: http://127.0.0.1:9000/vector
    method: post
    compression: none
    encoding:
      codec: "json"
    inputs:
      - remap